### PR TITLE
feat: new changes from sonner

### PR DESCRIPTION
**Pull request by sadeghbarati**
I checked every part of `sonner` code and brought it here, sometimes this error happens which I don't know how to solve please do have a look and submit a review, please

image

### CODE REVIEW

**Comment by sadeghbarati** [comment]
@xiaoluoboding Could you please review, Thanks 🙏

**Comment by sadeghbarati** [comment]
@xiaoluoboding Error seems gone now after updating deps,  : |

Can you please test it too?

**Comment by xiaoluoboding** [comment]
@sadeghbarati OK, I will check it and test the new changes.

**Comment by xiaoluoboding** [comment]
@sadeghbarati I apologize, but this pull request contains significant changes to the code formatting. It appears that we may have different formatting guidelines. Please remove any formatting changes and retain only the logical modifications.

**Comment by sadeghbarati** [comment]
I just used the antfu eslint config and then remove it from deps, ok I'll create the new PR

**Pull request closed without merging**
